org: averman
app: averism
service: user
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  deploymentBucket:
    name: averism-serverless

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
    authorizer:
      cognitoAuth:
        type: 'cognito'
        userPoolArn: 'arn:aws:cognito-idp:ap-southeast-1:368894314638:userpool/ap-southeast-1_1w7XYu9hm'
        userPoolClientId: '73g7s1vkbgf7vgknimupgaghsn'
        userPoolDomain: 'averman.auth.ap-southeast-1.amazoncognito.com'
        scope: 'openid email profile'
custom:
  customDomain:
    domainName: api.averism.com
    basePath: 'user'
plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket
  - serverless-domain-manager
