org: averman
app: averism
service: user
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  deploymentBucket:
    name: averism-serverless
  httpApi:
    name: user-api-service
    payload: '2.0'
    disableDefaultEndpoint: true
    cors: true
    authorizers:
      cognitoAuth:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.ap-southeast-1.amazonaws.com/1w7XYu9hm

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
          authorizer: cognitoAuth
custom:
  customDomain:
    domainName: api.averism.com
    basePath: ''
    createRoute53Record: true
    certificateName: 'api.averism.com'
    autoDomain: true

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket
  - serverless-domain-manager
